### PR TITLE
Feat: use `load_ipython_extension` to register magics

### PR DESCRIPTION
**Pull request by agoose77**
Users will now need to use `%load_ext jupyter_splitview` instead of `import jupyter_splitview`

### CODE REVIEW

**Comment by kolibril13** [comment]
Heyho, 
thanks for this pull request!
This is really convenient, however I have two thoughts on this:
1. Everybody who is already using this widget has to update their widget (but I guess that is ok for a 0.0.x version)
2. I like to have compatibility between python scripts and Jupyter cells.
When I copy+paste this cell to a python script I will get the error: 
```
    %load_ext jupyter_splitview
    ^
SyntaxError: invalid syntax
```
However, when I stay with the`import jupyter_splitview` I won't get an error with an implementation like this:
```py
from .sw_cellmagic import SplitViewMagic
from IPython import get_ipython  # register cell magic
import pkg_resources

__version__: str = pkg_resources.get_distribution(__name__).version

print(f"Jupyter Splitview v{__version__}")

try:
    ipy = get_ipython()
    ipy.register_magics(SplitViewMagic)

except AttributeError:
    print("Can not load SplitViewMagic because this is not a notebook")
```
What do you think is the prettier solution?
I think I'd slightly prefer the ``import jupyter_splitview` solution

**Comment by agoose77** [comment]
I personally think `load_ext` is a better solution - it makes it clear that you're using Jupyter features in a notebook, and registering them. Otherwise, in your pure-Python script, you'd end up with a useless import, which doesn't work well with tools like `isort`.

If you want to ensure that the notebook can be run as a script, you can add a cell tag to the cell that runs `%load_ext` e.g. `remove-cell`, and then use `nbconvert`'s `TagRemovePreprocessor` to remove it from the script:

```bash
jupyter nbconvert notebook.ipynb --TagRemovePreprocessor.remove_cell_tags="remove-cell" --to script
```

**Comment by kolibril13** [comment]
Nice! I will test this script later today and compare the pros and cons, but I am also thinking that `load_ext` is a good solution.

**Comment by kolibril13** [comment]
Here is now my comparison:
```py
import jupyter_splitview
# option to reload_extension ❌
# option to unload_extension ❌
# auto-complete ✅ 
# easy to remember ✅
# Copy&Paste to normal Python won't throw an error ✅
# clear that its a Jupyter features 🟡
```

```py
%load_ext jupyter_splitview
# option to reload_extension ✅ -> %reload_ext jupyter_splitview
# option to reload_extension ✅ -> %unload_ext jupyter_splitview
# auto-complete ❌ 
# easy to remember ❌
# Copy&Paste to normal Python won't throw an error ❌
# clear that its a Jupyter features ✅
```
Having auto-complete and not the need to remember the word `%load_ext` is a big benefit on the `import jupyter_splitview`, so right now I am again slightly on the side of keeping it ``import jupyter_splitview``

**Pull request closed without merging**
