### PR TITLE
Fix double import breaking all splits

### LINKED ISSUE #14: rerunning import cell kills splits

### PR DESCRIPTION
**Pull request by christopher-besch**
Closes #14

The `injected_dependency` nodes don't get deleted properly; this has to be fixed before merging.

### CODE REVIEW

**Comment by kolibril13** [comment]
Thanks for this contribution!
Reloading the import cell does not break the splitview widget anymore, however closing and re-opening the notebook will now make jupyter forget the css and javascript after these pr changes.

https://user-images.githubusercontent.com/44469195/173846622-310a9571-4dce-4d62-a3d5-13f9b5514816.mov

Only restarting the kernel of the reopened notebook and running the import brings back the javascirpt+css functionality.

**Comment by christopher-besch** [comment]
That's strange; I just tested this on my machine and I can't reproduce the issue...
I added some more debug logs. Could you reopen the notebook and paste the browser console output?

**Comment by kolibril13** [comment]
And one more important thing to note:
This bug does not occur, when one restarts the kernel before closing the notebook

**Comment by christopher-besch** [comment]
Ok, I know what the issue is. I'll fix it later today.

**Comment by christopher-besch** [comment]
Could you try this again, @kolibril13?

**Comment by kolibril13** [comment]
Really nice, now everything is working as expected. 
Excellent work!

**Review by kolibril13 — APPROVED** [review]

**Comment by christopher-besch** [comment]
Feel free to merge this now.

**Comment by kolibril13** [comment]
Looks great and does what it should do, thanks a lot for this contribution!

**Comment by kolibril13** [comment]
image

There are two merge conflicts right now,
can you once merge the last main into this branch?

**Review by kolibril13 — APPROVED** [review]

**Pull request merged**
